/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Elementos.Compra;
import Elementos.Tarjeta;
import Venta.ConsultaCompra;
import Venta.ConsultaTarjeta;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rlope
 */
public class MostrarMetodoDePago extends javax.swing.JFrame {

    /**
     * Creates new form MostrarMetodoDePago
     */
    public static Compra compraNueva=null;
    public static ArrayList<Tarjeta> lista=null;
    public MostrarMetodoDePago() throws IOException, SQLException{
        initComponents();
        
        ConsultaTarjeta consulta= new ConsultaTarjeta();
        lista=consulta.lista;
        MostrarTarjeta(lista);
        this.setLocationRelativeTo(null);
    }
    public MostrarMetodoDePago(Compra compra) throws IOException, SQLException{
        initComponents();
        compraNueva=compra;
        ConsultaTarjeta consulta= new ConsultaTarjeta();
        lista=consulta.lista;
        MostrarTarjeta(lista);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBlanco = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTarjeta = new javax.swing.JTable();
        btnrPag = new javax.swing.JButton();
        btnNtrgt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBlanco.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(111, 11, 11));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Franchise", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Formas de Pago");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tablaTarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaTarjeta);

        btnrPag.setText("Pagar");
        btnrPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrPagActionPerformed(evt);
            }
        });

        btnNtrgt.setText("Anadir ");
        btnNtrgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNtrgtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver))
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelBlancoLayout.createSequentialGroup()
                                .addComponent(btnNtrgt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnrPag, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrPag)
                    .addComponent(btnNtrgt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBlanco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        try{
            MostrarCarrito regreso = null;
            try {
                regreso = new MostrarCarrito();
            } catch (SQLException ex) {
                Logger.getLogger(MostrarMetodoDePago.class.getName()).log(Level.SEVERE, null, ex);
            }
            regreso.setVisible(true);
            
            super.dispose();
        }catch(IOException ex){
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnrPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrPagActionPerformed
        int fila = tablaTarjeta.getSelectedRow();
        if(fila>=0){
            JOptionPane.showMessageDialog(null,"Pago exitoso");
            ConsultaCompra conCompra = new ConsultaCompra();
            conCompra.subirCompra(compraNueva);
            menu pant1;
            try {
                pant1 = new menu();
                pant1.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MostrarCarrito.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }    
        else{
            JOptionPane.showMessageDialog(null,"Método de Pago no Seleccionado");
        }
        
    }//GEN-LAST:event_btnrPagActionPerformed

    private void btnNtrgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNtrgtActionPerformed
        // TODO add your handling code here:
        AnadirTarjeta pant;
        pant = new AnadirTarjeta();
        pant.setVisible(true);
                    
                    this.dispose();
      
          
    }//GEN-LAST:event_btnNtrgtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarMetodoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarMetodoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarMetodoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarMetodoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MostrarMetodoDePago().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MostrarMetodoDePago.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MostrarMetodoDePago.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNtrgt;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnrPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JTable tablaTarjeta;
    // End of variables declaration//GEN-END:variables
    
    

    private void MostrarTarjeta(ArrayList <Tarjeta> lista) {
         //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel tablita = new DefaultTableModel();
        tablita.addColumn("Nombre");
        tablita.addColumn("#Tarjeta");
        tablita.addColumn("Vencimiento");
        tablita.addColumn("CVV");
        tablaTarjeta.setModel(tablita);
        
        Object datos[]= new Object[4];
        for(int i=0;i<lista.size();i++){
            datos[0]=lista.get(i).getNombre();
            datos[1]=lista.get(i).getNum_tarjeta();
            datos[2]=lista.get(i).getFecha_vencimiento();
            datos[3]=lista.get(i).getNumeros_seguridad();
            tablita.addRow(datos);
        }
           
        tablaTarjeta.setModel(tablita);
        tablaTarjeta.setRowHeight(64);
       
    }
}
